language: python
stages:
- test
- coverage
install:
- pip install -r requirements.txt
script:
- python -m unittest tests
jobs:
  include:
  - python: 3.5
  - python: 3.5-dev
  - python: 3.6
  - python: 3.6-dev
  - python: 3.7-dev
  - stage: coverage
    python: 3.5
    script:
    - coverage run --source=RepositoryChecker -m unittest tests
    after_success:
    - coverage report -m
    - coveralls
  - stage: deploy
    python: 3.5
    script:
    - echo "No test for deploy"
    deploy:
      provider: pypi
      user: Nydareld
      password:
        secure: bWhu1NBLTFZfjsm6Y2G7TanRDQlxrGxbQKR32bHjfXpxV66INRMWxK4IXjR4aemBVnPgNtSjRAnoDAat5HzLdQBTF4ZHq5gsuyykdTxSQwuYpL74acZgttQl0uZxYDrM6/af5vZfLqbvhMznwSKYaIhhKYUGqnqfVP+z3V7sO/3Jc1nrWoORB2YT3Vd9D5Et3QuH0BPtHLmtuLJueDCKyXBu4TGhPquE+ipji+iVbjKHDjrNDKLp8TUWw6gUpWkrZ9uZ4ePo0DAlzGBRdRhGbxq900Tu73nSX+79gSdhtuai9ryZkW9JnwQk7NmfGOQyAA33cAi+DxHHz1ttnJBOhLIALQSYzB55nUzpBfBQnITwhKajcn+ltvScaUZr++cf7w46Aw7vJs7ZkXRAcnDj/DMR+g6rnb/25e5QP/XlyQhzkJ2jOeH3MO44dXyt5Yu69yDSrBzg72rjKYLLRiey6HOyxq+0LIleApO06pgGcXIaLti/5mNrmLc+iSZwBUto8vmDnq20i1lnit+FFGsZlQ/sXJpaF83MdGmciII2bYovxtRHfnknQVGzrL5/vGFxoGEvwNkNNTiHYUMYAQE0AGEWQJLqmZD2cDmgcfGqKsWwJ2caej7vvEmoGUBlTPzKzOjCZ9My3FmetKHCQr5Tb6XTvYuqdoLmHk+0J+pslYk=
      on:
        tags: true
